### PR TITLE
Use localhost for notification server

### LINKED ISSUE #5: Use only localhost for block notify port
The server listening for block notifications should  by default only listen on localhost.

@Emzy Could you add your suggestion?

### PR DESCRIPTION
**Pull request by chimp1984**
Fixes https://github.com/bisq-network/btcd-cli4j/issues/5

### CODE REVIEW

**Comment by mrosseel** [comment]
Is this configurable? #5 discusses this. If you run in docker containers btcd and seednode run on different hosts. Please give some more context on how you interpret #5 and how this PR would work with docker ok installations

**Comment by sqrrm** [comment]
> Is this configurable? #5 discusses this. If you run in docker containers btcd and seednode run on different hosts. Please give some more context on how you interpret #5 and how this PR would work with docker ok installations

Doesn't look easy to make configurable, best would be if you could forward the port to the docker container I think.

**Comment by chimp1984** [comment]
@mrosseel Feel free to provide a PR for supporting an option for the host.

**Review by sqrrm — APPROVED** [review]
ACK

**Pull request merged**
